# Generated by Django 6.0.1 on 2026-01-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, help_text='স্পেস দিয়ে লিখুন: USA JP Global', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(default='In Stock', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=models.CharField(default='1 Year Official Warranty Support', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='স্পেস দিয়ে লিখুন: Silver Black Orange', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, help_text='স্পেস দিয়ে লিখুন: 8GB 12GB 16GB', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, help_text='স্পেস দিয়ে লিখুন: 128GB 256GB 512GB', max_length=255, null=True),
        ),
    ]
